### ISSUE TITLE
How to handle detected coordinates, how is it normalized？

### ISSUE THREAD

**Issue by LinJM** [Ucas-HaoranWei/Vary-toy#28]
As the title asks, how does this model process the coordinate information in object detection? Is it normalized to 0 to 1 ? Is it necessary to refer to the input resolution of the Tiny module?

**Comment by Ucas-HaoranWei** [comment]
After normalizing to 0 to 1, the values expanded by 1000 times, as stated in the report.

**Comment by LinJM** [comment]
thanks
