### ISSUE TITLE
路径很奇怪

### ISSUE THREAD

**Issue by qin-yuhao** [Ucas-HaoranWei/Vary-toy#35]
![1718993150207](https://github.com/Ucas-HaoranWei/Vary-toy/assets/124507763/fc6bd72d-e6a8-441a-8f5e-b83a4233261a)
我明明指定的我的路径，它为什么还尝试加载原来的路径

**Comment by qin-yuhao** [comment]
噢噢，看见了，还有其他地方需要改

**Comment by qin-yuhao** [comment]
还是没懂为什么这里会报错

**Comment by Ucas-HaoranWei** [comment]
重新编译试试？
